export { default as Home } from './home/Home';
export { default as Product } from './product/Product';
export { default as Pricing } from './pricing/Pricing';
export { default as Blog } from './blog/Blog';
export { default as About } from './about/About';
export { default as Privacy } from './privacy/Privacy';
export { default as Message } from './message/Message';
export { default as Find } from './find/Find';
export { default as Login } from './login/Login';